### PR TITLE
Trying to fix the zip

### PR DESCRIPTION
**Pull request by gedankenstuecke**
Trying to just remove the broken pictures for now to see whether this makes the zip creation finally go through. c.f. #444

### CODE REVIEW

**Comment by gedankenstuecke** [comment]
It's a super ugly thing, but as the tests would all run through in `dev` it must be somehow related to our deployment. Think we could try merging this, run the `zipfulldata.rb` and see what happens now?

**Comment by philippbayer** [comment]
Yes let's try ^^

**Comment by philippbayer** [comment]
Server went down immediately, but the running Docker image is still 2 days old, looks like coincidence

**Comment by gedankenstuecke** [comment]
Cool, will you start The `sidekiq` task and monitor?

**Comment by philippbayer** [comment]
You mean `rake dump:full`? will do that now

**Comment by philippbayer** [comment]
Hmm looks like it ran out of memory again, server doesn't react right now... have to go to a kid's birthday soon but will keep on monitoring

**Pull request merged**
