### PR TITLE
[MRG] fixed message deleting + added tests, closes #391

### LINKED ISSUE #391: Deleting messages doesn't work
I'm getting an unauthorized when trying to delete a message on the production system.

### PR DESCRIPTION
**Pull request by gedankenstuecke**
With this #391 should be closed as you can delete messages you've received once again. It also adds some tests to the messages.

### CODE REVIEW

**Comment by gedankenstuecke** [comment]
All robot reviewers are fine, test coverage increases, bug is fixed. :shipit:

**Comment by tsujigiri** [comment]
Ah, I missed [the line in `require_owner`](https://twitter.com/HoracioMelvin/status/872222085657112577). Hm... whose `user_id` is this? The sender's?

**Comment by tsujigiri** [comment]
Who should be able to delete messages and should they still be visible to the other correspondent? Or is it enough for the sender to be able to delete messages, which then disappear for both?

**Comment by tsujigiri** [comment]
Also: `from_id` should be the same as `user_id`. `user_id` is checked in `require_user`. So, if I understand this correctly, this shouldn't even change anything. :question:

**Comment by gedankenstuecke** [comment]
I think this needs a not-so-short description:

The `user_id` gives the user who owns the message. Our message system duplicates each message when it's sent. So Alice(`user_id=1`) creates a message to Bob (`user_id=2`). What happens is that the message from Alice looks like this: 

`id: 1, user_id: 1, from_id: 1, to_id: 2, subject: "foo", body: "bar", sent: true`. 

The `message.rb` model duplicates this so that Bob owns a copy too: 

`id 2, user_id: 2, from_id: 1, to_id: 2, subject: "foo", body: "bar", sent: false`

Now each of them is capable of deleting their copy of the message from their respective in/outbox while the other one remains a copy of it. That's why we just need to check for ownership through `user_id` instead of the `to/from` field. And that's also the reason why `from_id != user_id` for received messages unless you message yourself. 

Does that help? 😄

**Comment by tsujigiri** [comment]
Ah, I wasn't aware of the duplicating part. Neat. :slightly_smiling_face:

**Comment by gedankenstuecke** [comment]
Oh, and see also `spec/features/messaging_spec.rb` that now also tests for 

1. deleting messages you received from other users
2. you can't access other user messages 

There's no explicit test for not deleting, but both are handled by `require_owner`, so guess that's okay for now?

**Comment by tsujigiri** [comment]
It's an improvement already. :wink:

**Comment by gedankenstuecke** [comment]
I was too tired yesterday night to figure out how to make the appropriate post-request via the tests. 😂

**Pull request merged**
