### PR TITLE
Getting this branch into the orga repo. 

### PR DESCRIPTION
**Pull request by gedankenstuecke**
Is there a cleverer way? :D

### CODE REVIEW

**Comment by tsujigiri** [comment]
Seems clever enough to me. ;)

**Comment by gedankenstuecke** [comment]
It's just that you have to create the branch manually before you can do the PR, wondered if there was a "pull request to a branch that would be newly generated" :smiley:

**Comment by tsujigiri** [comment]
I don't understand. :confused:

**Comment by gedankenstuecke** [comment]
so, `opensnp:rplots` didn't exist, as I started working on the thing in my fork, i.e. `gedankenstuecke:rplots`. In order to be able to pull request into `opensnp:rplots` instead of `master` I first had to create the new branch `opensnp:rplots` and then do the PR. A bit clearer now?

**Comment by tsujigiri** [comment]
You can open a pull request from your own branch as well.

**Comment by gedankenstuecke** [comment]
Yes, I did that. But you can not open a PR into a yet non-existing branch on the remote repository.

**Comment by tsujigiri** [comment]
What do you need `opensnp:rplots` for?

**Comment by gedankenstuecke** [comment]
for propagating my changes to a central place where you guys/other contributors can work on it too? because probably none of you check my fork? :wink:

**Comment by tsujigiri** [comment]
In this case you can just push to the new branch. No need for a pull request into a new branch.

**Comment by gedankenstuecke** [comment]
Ok, and can I push to a new branch open `opensnp` from my fork right away?

**Comment by tsujigiri** [comment]
You can push from your local branch if you added opensnp as a remote:

```sh
git remote add opensnp git@github.com:openSNP/snpr.git
git push opensnp rplots
```

**Comment by gedankenstuecke** [comment]
ah, of course. thanks :) :+1:

**Pull request merged**
