### PR TITLE
Added steps to initialize database

### PR DESCRIPTION
**Pull request by bverpaalen**
Postgres can be a bit of a struggle if you are not used to it so I added extra steps for creating a user and how to give it superuser rights

### CODE REVIEW

**Comment by gedankenstuecke** [comment]
That's really useful, thanks for that. Are these platform-dependent steps or should it work for any Unixy-system? Otherwise would be cool to at least give an idea on which system this works. 😊

**Comment by bverpaalen** [comment]
I ran them on Fedora 25. It should work for every linux distribution but I didn't test it

**Comment by bverpaalen** [comment]
Looks good. @ascheben is trying to install it on windows but it's quit the challenge.

**Comment by gedankenstuecke** [comment]
@philippbayer told me about that! We can merge that in later, when/if @ascheben succeeds (I can imagine it being a pain under Windows!)

**Pull request merged**
