### PR TITLE
add genomeprep link

### PR DESCRIPTION
**Pull request by gedankenstuecke**
Add link to repository with ~5,000 pre-processed and cleaned data sets to genotype page.

### CODE REVIEW

**Comment by philippbayer** [comment]
Sorry I just saw this PR - is there a reason why the checks are hanging?

**Comment by tsujigiri** [comment]
@philippbayer I think Travis CI stopped offering their free tier. Not sure what's wrong with CodeClimate. I started setting up GitHub Actions for that, but apparently I forgot about it soon after. :sweat_smile:

**Comment by philippbayer** [comment]
I see :) Can we turn off these two checks then? Especially your PR changes just one line

**Comment by tsujigiri** [comment]
At your own risk! :grimacing: The problem is that TravisCI also built the Docker image. But I can do that locally.

**Comment by tsujigiri** [comment]
I turned off the failing checks.

**Comment by philippbayer** [comment]
Thanks!!

AppVeyor has a open source free-tier, would it make sense to switch to them? https://www.appveyor.com/pricing/
or just use Github Actions like you started to?

**Comment by tsujigiri** [comment]
I'd go with GitHub Actions, since we don't need another account on another service for that. We just need to get it running...

**Comment by philippbayer** [comment]
> Failure/Error: expect(page).to have_content('Variations you did not enter yet (3)')
>       expected to find text "Variations you did not enter yet (3)" in "openSNP News Data Latest Data About Dogbert x Upload Your Genotyping File Upload the genotyping raw-data you got from 23andMe, deCODEme or FamilyTreeDNA to the openSNP database to share it with other personal-genomics customers and scientists from around the world. x Enter Your Variations Let us, and the other openSNP users, know some of your characteristics—like hair or eye color! Or how about some diseases? Whatever you feel like sharing!. x Enter a New Phenotype Got an idea for a phenotype that has not been asked about yet and that could have genetical roots? Great, you can add one to the openSNP database. xLogin successful! Hello, Dogbert Add your description Achievements Variations you did not enter yet (21)

Seems like the test fails because the DB does not get reset between tests any more? We expect 3 variations but the DB has 21

**Comment by tsujigiri** [comment]
@philippbayer Hmmm... Maybe it's leftover data from the old tests, running before the RSpec ones? :thinking: Let's try [this](https://github.com/openSNP/snpr/pull/539).

**Comment by gedankenstuecke** [comment]
Doh, of course that was the problem, thanks @tsujigiri!

**Pull request merged**
