### PR TITLE
Encrypt message body and subject

### PR DESCRIPTION
**Pull request by tsujigiri**

### CODE REVIEW

**Comment by philippbayer** [comment]
Very good idea :+1: - how come te Hound is hanging? Can this be merged?

**Comment by tsujigiri** [comment]
It would be great if someone could double check that the migration does what I think it does. Other than that it should be mergable.

**Comment by tsujigiri** [comment]
Fixed the hound issue. It was still ticked as a requirement, even though the integration changed, which is also why it was in there twice.

**Comment by tsujigiri** [comment]
> key must be 32 bytes

:wink:

**Comment by philippbayer** [comment]
One thing that could be fixed is to add a relevant line to .env.development and .env.test

**Comment by gedankenstuecke** [comment]
That sounds good, it's already the case for `.env.test` but could also be added for `.env.development` 👍

**Comment by tsujigiri** [comment]
Fixed. I also added a key to the deployment script, so this should be ready to be merged.

**Comment by gedankenstuecke** [comment]
Okay, looks ready to be merged to me!

**Comment by tsujigiri** [comment]
I'll just do it then. :wink:

**Comment by gedankenstuecke** [comment]
Let me fix the codeclimate thing :)

**Comment by gedankenstuecke** [comment]
well, looks like that didn't help :D

**Pull request merged**
