### PR TITLE
Update ruby to 2.7.7

### PR DESCRIPTION
**Pull request by philippbayer**
Shouuuuld make dependabot PRs work. heaps new monkeypatches to make Rails 4.2 work

### CODE REVIEW

**Review by tsujigiri — APPROVED** [review]
Hound doesn't look too happy. :wink: Other than that... :crossed_fingers:

**Review by gedankenstuecke — APPROVED** [review]
What @tsujigiri is saying! Don't thinkhte patches need to be edited to make the hound happy 🤞

**Comment by philippbayer** [comment]
Thanks! Good luck everyone :)

**Comment by philippbayer** [comment]
Re monkeypatches: in the longrun we can just delete those. With Ruby 2.7.7 we could technically update to Rails 6 (and 7)

**Pull request merged**
