### PR TITLE
Updates: Replaces sorting by created_at by sorting by ID, speed up the associated view

### PR DESCRIPTION
**Pull request by philippbayer**
The updates controller is a bit slow, here's one way to make it a bit faster - instead of sorting by the 'created_at' field we sort by the `id` field. In Rails, the `id` field by default has an index, while the `created_at` field usually doesn't have one (we didn't make any). Instead of making indexes everywhere I just sort by ID, since the order of ID follows the order of `created_at`.

Benchmark on production:
Old:
```
2.3.3 :002 >       Benchmark.measure {@new_genotypes = Genotype.order('created_at DESC').limit(20)
2.3.3 :003?>       @new_users = User.order('created_at DESC').limit(20)
2.3.3 :004?>       @new_phenotypes = Phenotype.order('created_at DESC').limit(20)
2.3.3 :005?>       @new_phenotype_comments = PhenotypeComment.order('created_at DESC').limit(20)
2.3.3 :006?>       @new_snp_comments = SnpComment.order('created_at DESC').limit(20)
2.3.3 :007?>   
2.3.3 :008 >         @newest_plos_paper = PlosPaper.order('created_at DESC').limit(20)
2.3.3 :009?>       @newest_mendeley_paper = MendeleyPaper.order('created_at DESC').limit(20)
2.3.3 :010?>   
2.3.3 :011 >         @newest_paper = @newest_mendeley_paper | @newest_plos_paper
2.3.3 :012?>       @newest_paper.sort! { |a, b| b.created_at <=> a.created_at } }
 => #<Benchmark::Tms:0x0000000379e5c0 @label="", @real=0.11413506604731083, @cstime=0.0, @cutime=0.0, @stime=0.010000000000000675, @utime=0.040000000000000036, @total=0.05000000000000071> 
```

New:
```
2.3.3 :015 >   Benchmark.measure{
2.3.3 :016 >      @new_genotypes = Genotype.order('id DESC').limit(20)
2.3.3 :017?>       @new_users = User.order('id DESC').limit(20)
2.3.3 :018?>       @new_phenotypes = Phenotype.order('id DESC').limit(20)
2.3.3 :019?>       @new_phenotype_comments = PhenotypeComment.order('id DESC').limit(20)
2.3.3 :020?>       @new_snp_comments = SnpComment.order('id DESC').limit(20)
2.3.3 :021?>   
2.3.3 :022 >         @newest_plos_paper = PlosPaper.order('id DESC').limit(20)
2.3.3 :023?>       @newest_mendeley_paper = MendeleyPaper.order('id DESC').limit(20)
2.3.3 :024?>   
2.3.3 :025 >         @newest_paper = @newest_mendeley_paper | @newest_plos_paper
2.3.3 :026?>       @newest_paper.sort! { |a, b| b.id <=> a.id } }
 => #<Benchmark::Tms:0x0000000330da88 @label="", @real=0.011255990713834763, @cstime=0.0, @cutime=0.0, @stime=0.0, @utime=0.0, @total=0.0> 
```

The difference for real time is 5-10x.

I'm sure this isn't the last fix here.

### CODE REVIEW

**Comment by philippbayer** [comment]
Still two super slow lines in the view:
```
<%= User.all.sort {|a,b| a.id <=> b.id}.index(nu) + 1 %>
<%= Genotype.all.sort {|a,b| a.id <=> b.id}.index(ng) + 1 %>
```

**Comment by philippbayer** [comment]
I have changed those two lines now - the controller once counts how many users and genotypes there are, and then just subtracts from that number when iterating over the last 20 items.

**Comment by gedankenstuecke** [comment]
Looks ready to merge to me?

**Comment by philippbayer** [comment]
Let's see :)

**Comment by gedankenstuecke** [comment]
👍

**Comment by philippbayer** [comment]
Deployed now. noticeably faster, but still one of the slower corners of the page

**Comment by gedankenstuecke** [comment]
Much better! And added two more improvements to #375

**Pull request merged**
