### PR TITLE
Remove Ruby version from Gemfile

### PR DESCRIPTION
**Pull request by tsujigiri**
Passenger complained that it couldn't find version 2.3 after I updated
the Docker image to use 2.4 and I'm not sure it makes sense to specify
the version if it has to be a specific one.

Alternatively we could set it to 2.4.3. This seems to even pin it to a patch level automatically. I'd expect this to be more problematic than helpful. What do you think?

### CODE REVIEW

**Comment by gedankenstuecke** [comment]
We had originally set it in the Gemfile after some discussion in #280 

(btw. the [.travis.yml](https://github.com/openSNP/snpr/blob/master/.travis.yml) still uses `2.3` it seems?)

I guess specifying the minimal version somewhere would be a good idea. But maybe we got to the wrong conclusion back then? I don't have a strong opinion either way. @philippbayer any take on that?

**Comment by tsujigiri** [comment]
Bundler doesn't seem to suppoert a "minimum version" in the first place and complains every time I run it.

**Comment by gedankenstuecke** [comment]
True, so we could remove the 'minimum version'. But then we should maybe provide a `.ruby-version` and update the `.travis.yml` to make sure we test against the version in production? :)

**Comment by tsujigiri** [comment]
Yes, let's do that.

**Pull request closed without merging**
