### PR TITLE
Revert "Remove ruby version from gemfile (#473)"

### PR DESCRIPTION
**Pull request by gedankenstuecke**
This reverts commit bea8df7084a70d89432825a193c283d7a9390e5f.

It seems the earlier commit crashed phusion so that the images can't start any longer.

### CODE REVIEW

**Comment by tsujigiri** [comment]
The deployment was already broken, due to the version mismatch. This one broke a test. I'm working on fixing it.

**Comment by gedankenstuecke** [comment]
Ah, gotcha, thanks!

**Comment by tsujigiri** [comment]
Oh, also: https://travis-ci.org/openSNP/snpr/builds/325627930#L745 😬

**Comment by gedankenstuecke** [comment]
😂

**Pull request closed without merging**
