### PR TITLE
cleans up user_is_user template

### PR DESCRIPTION
**Pull request by audy**
I was going to try cleaning up the users controller but ended up going on a hunt for a missing `<div>` instead. I ended up cleaning up the `_user_is_user` partial quite a bit. I mostly just fixed indentation and replaced some inline Ruby code with more concise equivalents.

I tested in development mode by clicking on stuff and everything seems to be in order.

### CODE REVIEW

**Comment by tsujigiri** [comment]
:honeybee:

**Comment by tsujigiri** [comment]
A test would still be nice, though. If you have the time. :wink:

**Comment by audy** [comment]
What kind of test? A view test? I usually just test that the page renders without raising an error when I don't have a lot of time.

--austin

**Comment by tsujigiri** [comment]
To increase test coverage I do the same. A simple feature test that opens the page should be enough. There were some issues. You can see them if you look into Gitter. ;)

**Pull request merged**
