### PR TITLE
modifies numbers:dump rake to generate JS for stats (`/statistics` hasn't been changed)

### PR DESCRIPTION
**Pull request by SXibolet**

### CODE REVIEW

**Comment by tsujigiri** [comment]
Could you change your indentation to 2 spaces?

**Comment by SXibolet** [comment]
sure! Just for JS or everything?

**Comment by tsujigiri** [comment]
Everything. Thank you! :smile:

**Comment by SXibolet** [comment]
Alright, that commit hopefully resolves the indentation in the files I touched. Let me know if you see something that's off & sorry for not preemptively keeping a consistent style!

**Comment by gedankenstuecke** [comment]
sorry, i didn't have any ☕  yet, but is there already a page where you can see how the new stats look like when cloning this PR? 😃

**Comment by SXibolet** [comment]
It's mostly an intermediate PR for generating the scripts from the live db. When cloning, I'd `mv static/new_statistics.html.erb static/statistics.html.erb`, and while in `public/data/plot_data`,  `wget https://opensnp.org/data/plot_data/number_users.js` and `wget https://opensnp.org/data/plot_data/number_pheno.js` after the live rake has been run (and the local rake hasn't been run---you'd just need to overwrite the js files if so).

**Comment by gedankenstuecke** [comment]
`NoMethodError: undefined method '[]=' for nil:NilClass
/home/app/snpr/lib/tasks/dump_numbers.rake:121:in block (4 levels) in <top (required)>`

This happened when I tried running the rake task to produce the JS files (on the production system).

**Comment by philippbayer** [comment]
Hmm I just ran it manually and it didn't throw up - 
I ran this piece (methods omitted)

```
pheno_and_upheno = Array.new(pp_n_wks){ Array.new(2) }
irb(main):044:0*  curr_n_pheno = 0
=> 0
irb(main):045:0>  Phenotype.find_each.with_index do |u,i|
irb(main):046:1* 
irb(main):047:1*         curr_n_pheno += 1
irb(main):048:1>         i = weeks_between(u.created_at.to_date, first_pheno_date)
irb(main):049:1>         pheno_and_upheno[i][0] = curr_n_pheno
irb(main):050:1> end
=> nil
irb(main):051:0>  curr_n_upheno = 0
=> 0
irb(main):052:0>  UserPhenotype.find_each.with_index do |u,i|
irb(main):053:1*        curr_n_upheno += 1
irb(main):054:1>         i = weeks_between(u.created_at.to_date, first_pheno_date)
irb(main):055:1>         pheno_and_upheno[i][1] = curr_n_upheno
irb(main):056:1> end
```

But is it supposed to have those nils?

```
irb(main):057:0> pheno_and_upheno
=> [[15, 73], [21, 185], [25, 288], [26, 367], [28, 387], [nil, 396], [nil, 403], [nil, 412], [31, 458], [44, 611], [45, 655], [nil, 667], [48, 689], [51, 720], [53, 740], [54, 769], [55, 792], [nil, 831], [nil, 833], [nil, 885], [nil, 941], [56, 981], [57, 1000], [59, 1010], [62, 1069], [73, 1281], [75, 1369], [82, 1509], [83, 1618], [nil, 1639], [84, 1736], [92, 2113], [94, 2318], [nil, 2388], [nil, 2471], [nil, 2571], [nil, 2585], [nil, 2597], [95, 2673], [nil, 2710], [97, 2767], [99, 2864], [102, 2950], [nil, 3022], [103, 3062], [104, 3118], [nil, 3137], [nil, 3159], [109, 3390], [116, 3539], [nil, 3709], [117, 3802], [118, 3938], [119, 4042], [123, 4190], [130, 4420], [131, 4548], [135, 4662], [136, 4796], [nil, 4868], [137, 4921], [nil, 4932], [141, 5113], [nil, 5251], [142, 5334], [144, 5509], [nil, 5858], [145, 6210], [146, 6340], [nil, 6366], [147, 6498], [nil, 6558], [148, 6642], [149, 6813], [151, 6861], [153, 6988], [154, 7127], [155, 7237], [158, 7282], [161, 7293], [nil, nil], [nil, nil], [nil, nil], [nil, nil], [nil, nil], [nil, nil], [nil, nil], [nil, nil], [nil, 7670], [nil, 7900], [164, 8205], [166, 8580], [nil, 8639], [nil, 8699], [nil, 9016], [167, 9176], [nil, 9253], [169, 9411], [172, 9623], [173, 9717], [nil, 9801], [175, 9826], [nil, 9852], [178, 9984], [nil, 10131], [179, 10155], [nil, 10166], [nil, 10280], [nil, 10314], [nil, 10359], [181, 10410], [nil, 10613], [182, 10650], [184, 10742], [185, 10781], [nil, 10870], [187, 11004], [nil, 11096], [nil, 11213], [188, 11449], [nil, 11621], [189, 11732], [192, 11903], [193, 11970], [198, 12324], [203, 12632], [204, 12903], [206, 13232], [209, 13853], [220, 14319], [221, 14480], [222, 14534], [224, 14617], [nil, 14734], [225, 14891], [nil, 14944], [229, 15397], [230, 15759], [233, 16094], [235, 16452], [238, 16669], [243, 17165], [244, 17267], [245, 17450], [246, 17700], [249, 18252], [254, 18621], [255, 18953], [nil, 19399], [nil, 19491], [256, 20157], [258, 20354], [260, 20505], [nil, 21125], [264, 21432], [nil, 21797], [265, 21978], [nil, 22229], [nil, 22267], [nil, 22374], [267, 22575], [nil, 22753], [nil, 22931], [nil, 22987], [270, 23175], [273, 23341], [nil, 23557], [274, 23844], [275, 23974], [276, 24171], [277, 24328], [281, 24504], [282, 24584], [283, 24918], [nil, 25002], [nil, 25024], [nil, 25357], [285, 25755], [287, 25951], [nil, 26486], [289, 26564], [nil, 26739], [nil, 26924], [294, 27303], [nil, 27558], [296, 27855], [297, 28118], [299, 28278], [306, 28494], [307, 28676], [nil, 28880], [308, 29033], [309, 29167], [nil, 29467], [310, 29603], [311, 29716], [312, 29873], [nil, 30252], [nil, 30394], [314, 30529], [nil, 30655], [320, 31316], [321, 31429], [nil, 31729], [nil, 31818], [nil, 31874], [323, 31906], [nil, 31984], [nil, 32058], [nil, 32075], [326, 32333], [327, 32666], [328, 33079], [330, 33269], [331, 33571], [335, 33919], [336, 34169], [nil, 34447], [nil, 34919], [nil, 35190], [337, 35407], [343, 35852], [nil, 36019], [344, 36229], [345, 36367], [nil, 36535], [nil, 36610], [356, 37338], [357, 37510], [360, 37738], [374, 37843], [375, 37908], [nil, 37977], [376, 38009], [379, 38185], [381, 38517], [nil, 38585], [382, 38691], [384, 38775], [nil, 38939], [nil, 39062], [385, 39385], [nil, 39567], [388, 39811], [391, 40343], [394, 40611], [nil, 40749], [395, 40898]]
```

So essentially you want a count of how often each phenotype appears in the user-phenotypes, right?

**Comment by SXibolet** [comment]
Right, the ``nil``s are just representative of a week in which no phenotypes were created. Another pass through the arrays will be required later to clean those up so the charts library doesn't fail. This PR was to generate live data for local testing of the new charts. If the rake runs once, it's served its purpose.

So it works if you run the entire rake on the production machine?

**Comment by SXibolet** [comment]
``pheno_and_upheno`` and ``users_and_geno`` just get a recursive sum for the respective pieces of data. The "resolution" of the sum is by week, so if 2 genotypes are added in the same week, that week has the value 2 plus last week's value.

The user-count and genotype-count are grouped (index 0, index 1) so that a plot can be easily generated with both lines. Similarly for phenotypes and user-phenotypes. This should reproduce https://opensnp.org/data/plot_data/pheno_plus_userpheno.png and https://opensnp.org/data/plot_data/geno_plus_phenotypes.png

**Comment by philippbayer** [comment]
It printed "Done!"

http://opensnp.org/data/plot_data/number_users.csv

http://opensnp.org/data/plot_data/number_phenotypes.csv

etc. were generated successfully - so it looks like it works? Does that data look like you're expecting it to look?

**Comment by SXibolet** [comment]
I actually left the CSV code in place, so those should be the same as before. The results are https://opensnp.org/data/plot_data/number_users.js and https://opensnp.org/data/plot_data/number_pheno.js
Interestingly, only ``number_users.js`` was generated!

**Comment by philippbayer** [comment]
https://opensnp.org/data/plot_data/number_pheno.js has now appeared too (weird?)

**Comment by SXibolet** [comment]
Chrome cache! Sorry for the hassle. It all looks good!
Also, I forgot I already implemented ``nil`` cleaning. It's just that you ran the phenotype code in isolation, so the cleaning didn't occur. So, I don't think the rake will need to be modified in a future PR --- just the frontend stuff.

**Comment by philippbayer** [comment]
No worries! Are these files enough for testing or do you need something else ran?

**Comment by SXibolet** [comment]
these files are all. Thank you!

**Pull request closed without merging**
