### PR TITLE
Refactor recommendations

### PR DESCRIPTION
**Pull request by tsujigiri**

### CODE REVIEW

**Comment by tsujigiri** [comment]
Sort of depends on #461 for that one added test.

**Comment by gedankenstuecke** [comment]
Wow, well done! 😍 

Is this basically an overarching PR that also includes #461?

**Comment by tsujigiri** [comment]
#461 Only contains the additional test case, that's useful. I could add it here and close the other one.

**Comment by gedankenstuecke** [comment]
Guess it already leads to a conflict 😉

**Comment by tsujigiri** [comment]
Should be good to go, now. 😉

**Comment by gedankenstuecke** [comment]
Wow, that was a lot of (urgently needed) work you put in there. Well done! 👍

**Comment by gedankenstuecke** [comment]
@tsujigiri right now I can't seem to find a single phenotype that has similar phenotypes. Should we run the recommender task to fix that? :D

**Comment by tsujigiri** [comment]
I don't think that will help. It shouldn't have changed in terms of how it works. I'll look into it.

**Comment by tsujigiri** [comment]
Interestingly, it works in the feature spec... 🤔

**Comment by tsujigiri** [comment]
Seems like it's not deployed yet.

**Comment by gedankenstuecke** [comment]
Ah right, let's wait and see then :)

**Comment by tsujigiri** [comment]
The Docker build is broken due to the new `.env`. 🎉

**Comment by gedankenstuecke** [comment]
That explains a lot. Are you having a look at it?

**Comment by tsujigiri** [comment]
Already fixed https://github.com/tsujigiri/opensnp.org-docker/commit/24a14d98754292f031220bba44738f06a2e2e945

... I hope. 😬

**Comment by gedankenstuecke** [comment]
I think so far that didn't help?

**Comment by tsujigiri** [comment]
Still no luck, it seems. But at least I didn't break anything that wasn't broken before. 😬 

Locally, I see Similar phenotypes, btw.... 🤔

**Comment by gedankenstuecke** [comment]
Mh... but did you run the phenotype recommendation task?

**Comment by gedankenstuecke** [comment]
Ok, I just called it manually, only some seconds after the `sidekiq` started to run the web server crashed. No clue how that comes. o_O

**Comment by tsujigiri** [comment]
I see similar phenotypes. now. Sidekiq is up and running and idle. In case you didn't know already. 😉

**Comment by gedankenstuecke** [comment]
I think that was time doing its thing! :D

**Pull request merged**
