### PR TITLE
Newsletter

### PR DESCRIPTION
**Pull request by gedankenstuecke**
As discussed on Gitter, here's the newsletter about 
* the survey by Sarah Nelson, and
* the winner of the *CrowdAI* competition done on our data. 

I ran the newsletter through the mailcatcher interface and it looks good on my end 👍

### CODE REVIEW

**Comment by gedankenstuecke** [comment]
Mh… Why exactly does the codeclimate `diff-coverage` fail, as basically nothing has changed? o_O @tsujigiri any ideas on that?

**Comment by tsujigiri** [comment]
No clue.

**Comment by gedankenstuecke** [comment]
Yeah, same for me here. I spent most of the day to set up a new computer, so I'll look into that tomorrow if no one else beats me to it.

**Comment by gedankenstuecke** [comment]
I couldn't figure out what was wrong. So I disabled that function in `codeclimate` for now and made some edits to the (super outdated) `ROADMAP.md` to trigger a new build there.

**Comment by gedankenstuecke** [comment]
I had to disable the corresponding option for `codeclimate` in the GH settings for this repo, but at last it did let me push. Could maybe one of you send out the newsletter later once it is live? (didn't get around to fishing my SSH keys out of the old machine).

**Comment by philippbayer** [comment]
Good idea to just turn off that test. All images have been deployed - 
just realised, this is the *survey* mailer, not the *newsletter* mailer, right? So sending will happen via 
``` sudo docker exec sidekiq bundle exec rake survey:send```, will turn that on now

**Comment by gedankenstuecke** [comment]
@philippbayer yep, that's the one! Also: Make sure to run it in a screen, otherwise it's hard to see when things go wrong!

**Comment by gedankenstuecke** [comment]
Oh, and of course thanks for starting it! 🎉 😍

**Comment by philippbayer** [comment]
No worries!
Already bumped into
```KeyError: key not found: "SURVEY_EMAIL_USER"```
fixing it

**Comment by gedankenstuecke** [comment]
Right, you have to specify the username, password etc. The ops repo has some details on it. Also: The bash history should give you a template for that.

**Comment by gedankenstuecke** [comment]
Worked, got the email! 👍

**Comment by philippbayer** [comment]
Nice :)

**Pull request merged**
