### PR TITLE
Removes pagination (#329)

### PR DESCRIPTION
**Pull request by 7yl4r**

### CODE REVIEW

**Comment by gedankenstuecke** [comment]
@7yl4r can one help you with making the fixes that @tsujigiri suggested? 😄

**Comment by 7yl4r** [comment]
Yes, I'm happy to do that. 

Honestly, I only kept the line long in an attempt to stay consistent with the rest of the file. 

If you like I can go through and clean up the formatting throughout. I would appreciate the opportunity to read through the code base as I'm doing so. Of course I have my own preferences, but if there a style guide you guys like I can follow that.

**Comment by tsujigiri** [comment]
That would be much appreciated! Our style guide is enforced by [Rubocop](https://github.com/bbatsov/rubocop). Since it's a lot of stuff that's not in order, we keep a `.rubocop-todo.yml`, for temporary exceptions that are supposed to be cleaned up over time. :wink: There is a `.rubocop.yml` with customizations to the [default rules](https://rubocop.readthedocs.io/en/latest/). There are three rake tasks to run rubocop with and without the TODOs and generate a new TODO list:

```
rake rubocop:generate_todos     # Generate new TODO file
rake rubocop:run                # Run rubocop
rake rubocop:run_without_todos  # Run Rubocop, don't show TODOs
```

Let us know if you need any help.

**Comment by 7yl4r** [comment]
I'm having a bit of trouble working out the other two calls to `will_paginate`. I'm familiar with templating and although ruby is new to me, the syntax seems straightforward. What I don't understand is where I should add the relevant properties to the (global?) `@snps` object being passed in `will_paginate(@snps)`. 

I'm imagining something like:
```
@snps.page_links=false
```

Or perhaps these calls to `will_paginate` should really be using `page_navigation_links` instead anyway?

Sorry I'm making so much trouble over this relatively simple fix because of my unfamiliarity with ruby. I'll be targeting javascript issues primarily from here on.

**Comment by tsujigiri** [comment]
No worries. What you need to do is add that option the the `will_paginate` call:

```ruby
will_paginate(@snps, page_links: false)
```

**Comment by gedankenstuecke** [comment]
Does that help @7yl4r? 😃

**Pull request merged**
