### PR TITLE
[WIP] added shirt/mug info

### PR DESCRIPTION
**Pull request by gedankenstuecke**
Will add a news item on the frontpage and puts the link to the shirt/mug in the footer.

### CODE REVIEW

**Comment by philippbayer** [comment]
Do you have to write `&amp;aff=6` instead of '&amp=6' in all the HTML? Can't remember

**Comment by gedankenstuecke** [comment]
Just `&` should be fine, see https://www.w3schools.com/tags/ref_httpmethods.asp

**Comment by philippbayer** [comment]
OK then :)

**Comment by gedankenstuecke** [comment]
Whops, I wanted to wait with merging that until Tuesday for a coordinated launch! That’s why the [WIP] for `work in Progress` 😂

**Comment by philippbayer** [comment]
Oops - didn't see the WIP, I need more sleep. Would people see this until the day after tomorrow?

**Comment by gedankenstuecke** [comment]
It will be in the email footer. But I guess that’s fine :)

**Pull request merged**
