### PR TITLE
Fix modal disappearance, closes #176

### LINKED ISSUE #176: Bug in Variations you did not enter
Hi
when in the section "Variations you did not enter", when you initially click on one (in thie case Astigmatism) I am greeted with a popup where you can either write a text to describe your variation or choose from the list below.

I initially clicked one of the options and the free text option on top disappeared. However, after reading the options I decided none of them really described my phenotype correctly so because I wanted to use the free text option I closed the popup without clicking OK

When I clicked on Astigmatism option again the free-text option would not show up again and one the multiple choice options was selected.

I believe if the user does not click ok and navigates out of the popup, the multiple choice he innitialy clicked should not be accepted as valid and thus when navigating back to the variation, the free-text option should be visible.

### PR DESCRIPTION
**Pull request by gedankenstuecke**
This is another super old bug that's been around for a while. 

The issue was (#176): If a user opens a phenotype-entry modal on their dashboard, checks one of the radio buttons and closes it, the text entry field will disappear and can't be recovered unless they're doing a hard reload of the page.

What happens after this fix, when a user closes the modal: 
* The hidden elements are shown again
* the selected checkbox will be unchecked. 

This is more how the modal should behave after re-opening.

### CODE REVIEW

**Comment by philippbayer** [comment]
Do we need an MT-M fixer in the parsing job as well? Right now only the rake tasks fixes everything, but that will only run once every few weeks

**Comment by gedankenstuecke** [comment]
This in principle only applies for new SNPs, right? Because already existing ones will not be overwritten?

**Comment by philippbayer** [comment]
Yes

**Comment by gedankenstuecke** [comment]
I'd say it's okay to keep it in like this for now, but can also adjust the parser if you think that's nicer :)

**Pull request merged**
